;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        crux-move-beginning-of-line
        easy-kill
        ))

(setq mc/cmds-to-run-once
      '(
        lsp-ui-doc--handle-mouse-movement
        ))
